[package]
name = "lexinode-backend"
version = "0.1.0"
edition = "2024"

license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
sqlx = { workspace = true }
lexinode-core = { path = "../lexinode-core" }
serde = { workspace = true }
uuid = { workspace = true }
pgvector = { workspace = true }
chrono = { version = "0.4.45", features = ["serde"] }

[dev-dependencies]
float-cmp = "0.10.0"