[package]
name = "lexinode-core"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
pgvector = { workspace = true }
chrono = { version = "0.4.45", features = ["serde"] }
thiserror = "2.0.20"

[dev-dependencies]
float-cmp = "0.10.0"

